<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezflow_democontent_clean",
                     "development" => false,
                     "summary" => "Home, Conference, Discussion Forum, Conference Blog, Live Video",
                     "description" => "This package contains the following nodes:\nHome - node\nConference - subtree\nDiscussion Forum - subtree\nConference Blog - subtree\nLive Video - subtree\n",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "contentobject",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "5.0.0",
                                           "named-version" => "5.0" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1163689610",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1163689610",
                                                  "person" => "Administrator User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "5.0",
                     "release-number" => "0",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentobject",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "contentobjects",
                                                "sub-directory" => "ezcontentobject" ) ),
                     "uninstall" => array( array( "type" => "ezcontentobject",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "contentobjects",
                                                  "sub-directory" => "ezcontentobject" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
