<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezflow_site_clean",
                     "development" => false,
                     "summary" => "eZ Flow (without demo content)",
                     "description" => "The eZ Flow extension to eZ Publish enables editors to build complex page layouts and pre-plan the publication schedule to ensure a constant flow of rich content.",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "site",
                     "extension" => false,
                     "install_type" => "import",
                     "ezpublish" => array( "version" => "5.0.0",
                                           "named-version" => "5.0" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1153313252",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "",
                                                  "person" => "Administrator User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array( "default" => array( array( "name" => "thumbnail.png",
                                                                      "subdirectory" => "",
                                                                      "type" => "thumbnail",
                                                                      "role" => "",
                                                                      "role-value" => "",
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "",
                                                                      "file-type" => "",
                                                                      "design" => "",
                                                                      "md5" => "d0a098ad93432761ff270ea553e549d4" ),
                                                               array( "name" => "logo.png",
                                                                      "subdirectory" => "",
                                                                      "type" => "image",
                                                                      "role" => "",
                                                                      "role-value" => "",
                                                                      "variable-name" => "image",
                                                                      "path" => "",
                                                                      "file-type" => "",
                                                                      "design" => "",
                                                                      "md5" => "ec4c8c048e629f3f6aa320cb7817ffc7" ) ) ),
                     "simple-file-list" => array(),
                     "version-number" => "5.0",
                     "release-number" => "0",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array( array( "type" => "ezpackage",
                                                                          "name" => "ezwt_extension",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezstarrating_extension",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezgmaplocation_extension",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezwebin_extension",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezflow_extension",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezflow_classes",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezflow_democontent_clean",
                                                                          "min-version" => "5.0" ),
                                                                   array( "type" => "ezpackage",
                                                                          "name" => "ezflow_design",
                                                                          "min-version" => "5.0" ) ),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array(),
                     "uninstall" => array(),
                     "settings-files" => array( "ini-site.php",
                                                "ini-admin.php",
                                                "ini-common.php",
                                                "ezflowinstaller.php",
                                                "install-scripts.php",
                                                "roles.php",
                                                "preferences.php" ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
