<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "plain_site",
                     "development" => false,
                     "summary" => "Plain site",
                     "description" => "Stripped install. Contains no special toolbar or menu choices",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "site",
                     "extension" => false,
                     "install_type" => "import",
                     "ezpublish" => array( "version" => "3.8.0",
                                           "named-version" => "3.8" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1135600234",
                                           "host" => "localhost:8085",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "",
                                                  "person" => "Administrator User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array( "default" => array( array( "name" => "thumbnail.png",
                                                                      "subdirectory" => "",
                                                                      "type" => "thumbnail",
                                                                      "role" => "",
                                                                      "role-value" => "",
                                                                      "variable-name" => "thumbnail",
                                                                      "path" => "",
                                                                      "file-type" => "",
                                                                      "design" => "",
                                                                      "md5" => "01ba8f7e2dd0368bfaeaa31d8441a8e8" ) ) ),
                     "simple-file-list" => array(),
                     "version-number" => "1.1",
                     "release-number" => "2",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array(),
                     "uninstall" => array(),
                     "settings-files" => array( "ini-site.php",
                                                "ini-admin.php",
                                                "ini-common.php",
                                                "roles.php",
                                                "preferences.php" ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
