<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezdemo_democontent",
                     "development" => false,
                     "summary" => "",
                     "description" => "",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "contentobject",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "5.0.0",
                                           "named-version" => "5.0" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1300109477",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1300109477",
                                                  "person" => "Administrator User",
                                                  "email" => "bk@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array( "b476ae30e0a67e8c3b542747dd3caa5c" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/search-result-clustering-with-ez-find/443-3-eng-GB/Search-Result-Clustering-with-eZ-Find.png",
                                                                                               "package-path" => "simplefiles/274b087e.jpg" ),
                                                  "7aca712855270c7826e1fb5ce5d30090" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/multivariate-testing/467-11-eng-GB/Multivariate-Testing.png",
                                                                                               "package-path" => "simplefiles/b0839e1d.jpg" ),
                                                  "cb48c01e310c2b3933cdc0661c4a618a" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/improved-online-analytics/479-3-eng-GB/Improved-Online-Analytics.png",
                                                                                               "package-path" => "simplefiles/7a3d11eb.jpg" ),
                                                  "c292efaba899d1e2bf49a86e5aecbc30" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/getting-started-with-ez-publish-etna/491-3-eng-GB/Getting-Started-with-eZ-Publish-Etna.jpg",
                                                                                               "package-path" => "simplefiles/a16f7354.jpg" ),
                                                  "114df3fbb84cbf9c7533d9e1f36f53a4" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/amazon-side-river/223-1-eng-GB/Amazon-Side-River.jpg",
                                                                                               "package-path" => "simplefiles/7d1afcb4.jpg" ),
                                                  "c882d324a7ace933807c1fb269e984d5" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/river-boat/228-1-eng-GB/River-Boat.jpg",
                                                                                               "package-path" => "simplefiles/bbbbc2fe.jpg" ),
                                                  "5c535315cb437330233390b557e3606c" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/flying-bird/233-1-eng-GB/Flying-Bird.jpg",
                                                                                               "package-path" => "simplefiles/9675a24a.jpg" ),
                                                  "fcc238fe34b5cae12086428a3d06ffea" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/turtles/238-1-eng-GB/Turtles.jpg",
                                                                                               "package-path" => "simplefiles/236e8a89.jpg" ),
                                                  "c00d7c512b8a507c21f68dd8a962fc5d" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/hat-on-a-stick/243-1-eng-GB/Hat-on-a-Stick.jpg",
                                                                                               "package-path" => "simplefiles/2233e737.jpg" ),
                                                  "5ab5d4d88a4036a848fbdcc5aba52f33" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/heron-in-the-water/248-1-eng-GB/Heron-in-the-Water.jpg",
                                                                                               "package-path" => "simplefiles/347b47f7.jpg" ),
                                                  "cf2b5b3ff0459e992efb6b3ebef8e85f" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/bird-island/253-1-eng-GB/Bird-Island.jpg",
                                                                                               "package-path" => "simplefiles/1c936c89.jpg" ),
                                                  "b2ae62ab2a5defaef82e2d1f20ec99fd" => array( "original-path" => "var/ezdemo_site/storage/images/travel/peruvian-amazon/aligator/258-1-eng-GB/Aligator.jpg",
                                                                                               "package-path" => "simplefiles/81b898d7.jpg" ),
                                                  "ed8092df1024eb39618d4b5598950522" => array( "original-path" => "var/ezdemo_site/storage/original/application/a1ec03af36d81e9b8c4f5022b13de7c2.m4v",
                                                                                               "package-path" => "simplefiles/8650bb68.m4v" ),
                                                  "f8a4d17a43243d1289dbfcb3077b2d93" => array( "original-path" => "var/ezdemo_site/storage/images/travel/information/largest-city-without-road-connection/266-1-eng-GB/Largest-City-Without-Road-Connection.jpg",
                                                                                               "package-path" => "simplefiles/e410cf0a.jpg" ),
                                                  "6407c9cdfd5d16ae56ad91fb8e425e65" => array( "original-path" => "var/ezdemo_site/storage/images/travel/information/amazon-jungle/285-4-eng-GB/Amazon-Jungle.jpg",
                                                                                               "package-path" => "simplefiles/44525552.jpg" ),
                                                  "63183f14981309421adc20de240d6ef0" => array( "original-path" => "var/ezdemo_site/storage/images/travel/information/floating-village-in-iquitos-loreto/297-3-eng-GB/Floating-Village-in-Iquitos-Loreto.jpg",
                                                                                               "package-path" => "simplefiles/1adcd08a.jpg" ),
                                                  "47a625f70eb48502d21359054a41a2fe" => array( "original-path" => "var/ezdemo_site/storage/images/city-shopping/products/new-york-cab/339-1-eng-GB/New-York-Cab.jpg",
                                                                                               "package-path" => "simplefiles/e627f43d.jpg" ),
                                                  "d03cb0f0ca042a830fbad9886ef9ed8a" => array( "original-path" => "var/ezdemo_site/storage/images/city-shopping/products/city-view/362-1-eng-GB/City-View.jpg",
                                                                                               "package-path" => "simplefiles/5b3249df.jpg" ),
                                                  "dbf5a6dc4e56d637f07bdc63807000d0" => array( "original-path" => "var/ezdemo_site/storage/images/city-shopping/products/street-crossing/373-1-eng-GB/Street-Crossing.jpg",
                                                                                               "package-path" => "simplefiles/01a8f40b.jpg" ),
                                                  "68ec6922551353ce21604ec422c6316e" => array( "original-path" => "var/ezdemo_site/storage/images/city-shopping/locations/new-york-city/391-2-eng-GB/New-York-City.jpg",
                                                                                               "package-path" => "simplefiles/90bbe723.jpg" ),
                                                  "344717be52aada472d23ae50a19f2599" => array( "original-path" => "var/ezdemo_site/storage/original/image/e76c8776dccaba21cbfc21f52a02e19f.png",
                                                                                               "package-path" => "simplefiles/7095dbbb.png" ),
                                                  "d5fb94aa39f233d3f1c271c42df17a40" => array( "original-path" => "var/ezdemo_site/storage/original/image/5abdfbefae47de9dca63bc43e3a23ff4.png",
                                                                                               "package-path" => "simplefiles/783983ef.png" ) ),
                     "version-number" => "5.0",
                     "release-number" => "0",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentobject",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "contentobjects",
                                                "sub-directory" => "ezcontentobject" ) ),
                     "uninstall" => array( array( "type" => "ezcontentobject",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "contentobjects",
                                                  "sub-directory" => "ezcontentobject" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
